default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + ENV.fetch("GOOD_JOB_MAX_THREADS", 4).to_i %>
development:
  <<: *default
  host: localhost
  database: promptspot_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  database: promptspot_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: ENV['DATABASE_URL']
